source "https://rubygems.org"

gem "addressable"
gem "middleman", "~> 4.1.14"
gem "middleman-autoprefixer", ">= 2.8.0"
gem "middleman-blog", ">= 4.0.1"
gem "middleman-livereload", ">= 3.4.6"
gem "middleman-minify-html", ">= 3.4.1"
gem "middleman-syntax", ">= 3.0.0"
gem "middleman-gh-pages"
gem "redcarpet"
gem "pry"
